// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okctudlvhkpqygyqssta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rY3R1ZGx2aGtwcXlneXFzc3RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDkyMTYsImV4cCI6MjA2NDY4NTIxNn0.LmwDEGDiscTZdtJ191W6b6Ji4yKOVn1InYai-KidwuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);